image: python:latest

stages:
  - test
  - deploy

test-all:
  stage: test
  script:
    - pip3 install html5lib
    - python3 -m unittest -v

deploy-pypi:
  stage: deploy
  when: manual
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - pip install wheel 
    - pip install twine
    - python setup.py sdist bdist_wheel
    - twine upload dist/*
