version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest


    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install html5lib

      # run tests!
      - run:
          name: run tests
          command: |
            python -m unittest -v

